FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY license_server /license_server
COPY config.ini /license_server/

WORKDIR /license_server
CMD ["python", "license_server.py", "config.ini"]
EXPOSE 6067