FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY scada_in /scada_in
COPY config.ini /scada_in/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /scada_in
ENV FLASK_DEBUG=1
CMD ["python", "scada_in.py", "config.ini"]

EXPOSE 6069
